### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by epage** [andoriyu/cargo-suity#3]
Avoid having to compile `cargo-suity` within everyone's CI.

Ideally, compatible with [trust's install.sh](https://github.com/japaric/trust) so people can easily consume them.

**Comment by andoriyu** [comment]
If you haven't started on it — I can work on this.

**Comment by epage** [comment]
I haven't.  I've not had much time lately (and divided between too many projects).  I'm just starting to wrap up the ground work for #2.  The nice thing is it'll stream the events as they come, which would give you the opportunity to timestamp the events and add timing information to the Junit.

**Comment by andoriyu** [comment]
Well, after hours of battling azure it's [done](https://github.com/andoriyu/cargo-suity/releases/tag/v0.2.1).

`install.sh` from trust should be able to install it.

**Comment by epage** [comment]
Great!

btw in case you didn't see my post, https://www.reddit.com/r/rust/comments/aw4b1g/azure_pipelines_for_rust_projects/ehk7gx6/?st=jsqisnia&sh=95273835

**Comment by andoriyu** [comment]
@epage Neat. Beat me to it, I was planning on doing the same thing and writing about it haha. I want to write some tasks and publish them to market place though.

**Comment by epage** [comment]
I'm still coming up to speed on Azure Piplelines, so not familiar with this market place you speak of.
